/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainwin (void);
GtkWidget* create_opts (void);
GtkWidget* create_about (void);
GtkWidget* create_vramtiles (void);
GtkWidget* create_console (void);
GtkWidget* create_diss (void);
GtkWidget* create_codes (void);
